name: Generate Snake Animation

on:
  # Jalankan otomatis setiap jam 00:00 (Tengah Malam)
  schedule:
    - cron: "0 0 * * *" 
  
  # Tombol agar bisa dijalankan manual
  workflow_dispatch:
  
  # Jalankan setiap kali ada update di branch main
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Membuat animasi snake dari grid kontribusi github-mu
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Mendorong (push) file SVG yang sudah jadi ke branch bernama 'output'
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
